### ISSUE TITLE
Uptdate discontinued for much devices

### ISSUE THREAD

**Issue by paolo-caroni** [lineageos4microg/lineageos4microg.github.io#100]
It seems that updates are more or less frequent depending on the device.
For example a5y17lte have three update on May and FP3 have zero at the moment.
In theory yhe builds would be twice a month (https://github.com/lineageos4microg/docker-lineage-cicd/issues/197#issuecomment-918110759) but it isn't.

**Comment by bananer** [comment]
There were some issues in the last few build rounds, but things should be stabelized for 18.1 and 19.1 now.

FP3 finished building a few hours ago.

**Comment by paolo-caroni** [comment]
Thanks
