### ISSUE TITLE
About updates of 15.1 builds

### ISSUE THREAD

**Issue by Kommprog** [lineageos4microg/lineageos4microg.github.io#101]
Will any further updates of LOS 15.1 builds for [bullhead](https://download.lineage.microg.org/bullhead/) be released? 
There were two last ones during one week and more than month ago, but support was dropped according to that [closed issue](https://github.com/lineageos4microg/docker-lineage-cicd/issues/298#issuecomment-1125166546), do I correctly understand?

**Comment by Kommprog** [comment]
@bananer Could you please answer, what's going on with 15.1 builds? Was they finally dropped or what?

**Comment by bananer** [comment]
Still the same:

> Right now we're lacking time and resources to support other versions.
>
> If you want to help, build it yourself and report whether it's working or not.
