### ISSUE TITLE
Build Server Issues for version 19.1?

### ISSUE THREAD

**Issue by mddvul22** [lineageos4microg/lineageos4microg.github.io#105]
I don't know how the build server works, but it would appear that there is an issue with the build server and version 19.1.  It appears that perhaps a build for one device (discovery, perhaps?)  is failing and causing all builds after that to not get built?  Perhaps the builds occur in alphabetical order?  Some devices, like blueline are getting built every few weeks.  However, many other devices, like fajita and flame, haven't been built in over a month.

**Comment by D3SOX** [comment]
Probably the wrong repo but yeah I'm waiting for it to build 19.1 for `kebab`.
Can someone maybe re-run the failed builds? Otherwise I'll have to wait until October 7th to finally get Android 12

**Comment by ramos** [comment]
It seems that the problem persists. Builds failed again for devices after discovery. Any tips on how to get 19.1?

**Comment by D3SOX** [comment]
See https://github.com/lineageos4microg/docker-lineage-cicd/issues/341 this issue is in the wrong repo

**Comment by mddvul22** [comment]
My devices are fajita and flame. I now have updates for those devices. Since I opened this ticket, I will now close it. Thanks!
