### ISSUE TITLE
Axolotl builds do not get updates since 17.10.2022

### ISSUE THREAD

**Issue by 1Maxnet1** [lineageos4microg/lineageos4microg.github.io#107]
I'm running lineageOS4microG on my SHiftphone 6mq (shift-axolotl). The website states, there are updates every two weeks. However I didn't receive any updates for over a month now. Is there any place where I can check the status or whether there are any issues?

**Comment by HaykCS01** [comment]
Me to...vayu

**Comment by 1Maxnet1** [comment]
I don't have any information what was wrong, but I got a new update now. Just installing it. I will close the issue when the update is done successfully. For the future, it would be nice if it is documented somewhere, how I can see what is wrong and why the intermediate updates were not available.

**Comment by HaykCS01** [comment]
I'm using clean LOS now, and my current update is December 2
