### ISSUE TITLE
Not clear where to report missing builds

### ISSUE THREAD

**Issue by devdan** [lineageos4microg/lineageos4microg.github.io#122]
The flow chart on the L4M page describes some scenarios. However, where do you report if builds are outdated or missing. In my case, the L4M builds are 2 months behind the official LOS builds.

**Comment by constantitus** [comment]
Yea, I have the same issue with the builds for guacamoleb. The latest microg for lineageos build for guacamoleb is 20230705, and the earliest lineageos build is 20230710, and they don't keep earlier builds on their downloads section

**Comment by petefoth** [comment]
Report missing builds EITHER
- here OR
- in [the XDA Forums thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/)

> the L4M builds are 2 months behind the official LOS builds.

LOS release builds weekly for 19.1 and 20.0 branches, and monthly for 18.1. We build monthly, the build run starts on the first day of the month, and takes around 16 days to complete.

**Comment by petefoth** [comment]
Added text to the README in [this commit](https://github.com/lineageos4microg/docker-lineage-cicd/pull/485/commits/9a4e15ea78b4094db51d3e565dcb9850e290ef34) The text will find ts way to the web site eventually :)
