### ISSUE TITLE
Files for Sony Xperia Z3 Compact (z3c) is missing

### ISSUE THREAD

**Issue by fractalf** [lineageos4microg/lineageos4microg.github.io#131]
First, thanks for providing MicroG and LineageOS builds! :) 

Build files for Sony Xperia Z3 Compact (z3c) is missing

https://download.lineage.microg.org/z3c/

Is this a bug in the build script or are these not supported anymore?

I installed this just a few months back, was working fine! ..but now the files are gone

![image](https://github.com/lineageos4microg/lineageos4microg.github.io/assets/5707457/be69fde0-7553-473e-a8f8-e61c77949af7)

**Comment by petefoth** [comment]
LineageOS dropped support for 18.1 devices, including this device, quite a while ago.

The final builds for most 18.1 devices are available at 
https://web.archive.org/web/20240527093848/https://download.lineage.microg.org/archive/

The final builds for Z3 Compact was `lineage-18.1-20240319-microG-z3c.zip`, which is available - with the other files from that build - at https://web.archive.org/web/20240527184212/https://download.lineage.microg.org/archive/z3c/

**Comment by fractalf** [comment]
The actually made some new builds...

https://download.lineage.microg.org/z3c/

![Image](https://github.com/user-attachments/assets/211d7a10-14f6-408a-a9a4-bfb90afa99fb)

**Comment by petefoth** [comment]
> The actually made some new builds...
> 

Yes - see https://github.com/lineageos4microg/docker-lineage-cicd/issues/738 for details
