### ISSUE TITLE
super_empty.img missing

### ISSUE THREAD

**Issue by attisimon** [lineageos4microg/lineageos4microg.github.io#135]
Hello!

This file is missing from download:
https://download.lineage.microg.org/FP5/lineage-21.0-20240521-microG-FP5-super_empty.img

The super_empty.img from the official LineageOS FP5 build can be used, the checksum is the same.

**Comment by petefoth** [comment]
The `..super_empty.img` file is now present for all builds still on the server https://download.lineage.microg.org/FP5/
