### ISSUE TITLE
beyond2lte has wrong version in latest release

### ISSUE THREAD

**Issue by BallsackJohnson** [lineageos4microg/lineageos4microg.github.io#136]
lineage-21.0-20240703-microG-beyond2lte.zip contains the files for the previous release which is still on LOS20. 
Recovery seems fine.

https://download.lineage.microg.org/beyond2lte/?sort=time&order=desc

**Comment by BallsackJohnson** [comment]
its been 4 days, I will throw in a Steam code for the game "Art of Rally" to whoever fixes it.

**Comment by petefoth** [comment]
The offending build has been replaced
