### ISSUE TITLE
Replace Yalp Store with Aurora Store in the FAQ

### ISSUE THREAD

**Issue by Lonser** [lineageos4microg/lineageos4microg.github.io#32]
Hey, just a small thing :) 
In the FAQ under:
Can I install apps from the Play Store on this ROM?
You mention:
Another solution is to use a local app, like Yalp Store.
I think that tip is great because a lot of users want to install apps from the Play Store but unluckily Yalp Store is abondoned. No Updates after 1 year. 
The best alternative I could find was Aurora Store, so you could maybe just replace Yalp Store with Aurora Store :) 
https://f-droid.org/en/packages/com.dragons.aurora/

**Comment by petefoth** [comment]
Closing. No mention of Yalp on the current web site
