### ISSUE TITLE
Officially suported OnePlus 6T and 7 Pro missing from downloads page

### ISSUE THREAD

**Issue by prurigro** [lineageos4microg/lineageos4microg.github.io#34]
They were both officially supported by LineageOS a few weeks ago but aren't on the [MicroG LineageOS downloads page](https://download.lineage.microg.org/) (I assume that means the builder hasn't included them yet).

Official LineageOS download pages for each device:
6T: https://download.lineageos.org/fajita
7 Pro: https://download.lineageos.org/guacamole

Thanks!

**Comment by BoBeR182** [comment]
Any updates I am also waiting for this to be officail?

**Comment by petefoth** [comment]
Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
