### ISSUE TITLE
no more weekly updates for beryllium / Xiaomi Poco F1 lineageOS despite new nightlies on lineageOS

### ISSUE THREAD

**Issue by gongoscho** [lineageos4microg/lineageos4microg.github.io#36]

**Comment by petefoth** [comment]
Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
