### ISSUE TITLE
[Device] Fajita (OnePlus 6T) Missing From Downloads

### ISSUE THREAD

**Issue by nummersyv** [lineageos4microg/lineageos4microg.github.io#38]
Hi.

Sorry if this is the wrong place to raise this issue.

LineageOS 16.0 is officially available for the 6T [here](https://download.lineageos.org/fajita), but I can't seem to find it on [download.lineage.microg.org](https://download.lineage.microg.org/) even though the website states that you "build LineageOS for microG for every device supported by LineageOS".
Since the device is indeed listed in the [build targets](https://github.com/LineageOS/hudson/blob/master/lineage-build-targets) I'm assuming the downloads are missing due to build failures. In this case, is there anything I can do to help as an owner the device?

Thanks for your work.

**Comment by mihaisumedre** [comment]
Hello! Fajita (officially supported by Lineage) is still missing as of 17 jan 2020. Can anyone help with the build? Thanks!

**Comment by tobiasKaminsky** [comment]
I can only offer you my personal build:
https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-563903258

I will update this from time to time.

**Comment by mihaisumedre** [comment]
> I can only offer you my personal build:
> [lineageos4microg/docker-lineage-cicd#62 (comment)](https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-563903258)
> 
> I will update this from time to time.

Hello, Tobias. I'm just about to try your build as it seems there is no official fajita release in sight. Perhaps you might have a more up to date one and willing to share it? The one from the previous comment has the date 9 december it the filename. Thanks a lot!

**Comment by tobiasKaminsky** [comment]
I will build a new one today afternoon

**Comment by mihaisumedre** [comment]
> I will build a new one today afternoon

That's great to hear! I'll happilly waiting. Is is already rooted? If not, what do you use for root? And what is the procedure you follow for upgrading? Thanks a lot, Tobias!

**Comment by tobiasKaminsky** [comment]
It is not rooted, and I did not tried to root it.
I guess that the regular su addon should work?

**Comment by tobiasKaminsky** [comment]
New version/link in https://github.com/lineageos4microg/docker-lineage-cicd/issues/62#issuecomment-587864582

**Comment by mihaisumedre** [comment]
Great! Although, I can only see two new files: md5 and sha256. The zip file is still the old one. Perhaps not uploaded, yet? Thanks!

**Comment by mihaisumedre** [comment]
Ok, it just popped up. I guess it wasn't fully uploaded. Thanks again, Tobias!

**Comment by petefoth** [comment]
Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
