### ISSUE TITLE
No recent builds for device “whyred”

### ISSUE THREAD

**Issue by OlivierNicole** [lineageos4microg/lineageos4microg.github.io#47]
The whyred device has recently come back into LineageOS official support. However, the builds present on the website are all from 2018.

Thanks for all your work!

**Comment by petefoth** [comment]
Closing as whyred is no longer supported, and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
