### ISSUE TITLE
No builds for m8

### ISSUE THREAD

**Issue by sebescudie** [lineageos4microg/lineageos4microg.github.io#54]
hello there,

hope I'm reporting to the right place. I could not find builds for m8 devices. the site only offers m8d images, which are not compatible with the m8.

will those be available again?

thanks.

**Comment by petefoth** [comment]
Closing as m8 is no longer supported, and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
