### ISSUE TITLE
FP3 November 12th update fails

### ISSUE THREAD

**Issue by Pratched** [lineageos4microg/lineageos4microg.github.io#62]
**Describe the bug**
I dont really know where else to report it and cannot find any other information. Everything worked quite fine when I migrated from the unofficial Lineage16 to the official version, except that It wiped the user data.
Anyway I reconfigured everything and used it mostly fine. Sometimes there are location issues but nothing serioues or longterm.
However the update from November 12th cannot be installed. Either it fails to install after downloading directly the update shows the same update after reboot again. I was able to reproduce the latter behaviour by clean installing with TWRP the .zip and upfront data wipe.

**To Reproduce**
1. Go to updater
2. Download
3. Install
4a. Installation fails -- Error
4.b Installation succeeds -- Reboot
5. Updater shows the update again.

**Expected behavior**
Plain simple updates.

**System**
Android Version:9
Custom ROM: LineageOS 16 for FP3

**Additional context**
Also it seems there isnt a newer version than the November build? 
I quite like microG and would love to continue using it.
If this is the wrong place to share this issue and you know better, please share.

In addition I had to experience the hard way, that when locking oem after installation, all user data is wiped and you have to reconfigure again.

**Comment by dotsumae** [comment]
I have the exact same issues, including learning the hard way about locking oem x) Apologies about the fake hope for help from the notification. At least I hope my answer raises this issue's visibility.

**Comment by ArchangeGabriel** [comment]
There has been a December 10th build since. Is there the same issue with it?

Also, [upstream moved to 17.1](https://download.lineageos.org/FP3) now. I don’t know when to expect the newest build for FP3, but this might change a lot of things too.

**Comment by Pratched** [comment]
Well I will not try to flash the new package again, since I cannot bear setting up my phone again, but I installed the latest via the updater and it proceeded. However the latest update from 10th Decemeber is still showing and I could try installing it again.

**Comment by Pratched** [comment]
Jut fyi, dont I sideloaded LOS17 (20210127) and found the update for 20210127 immediately after booting in the updater. I installed the update, rebooted and there it was again. So basically the same behaviour than with LOS16.
