### ISSUE TITLE
Serious bugs in Z3 builds from December and January

### ISSUE THREAD

**Issue by jw243** [lineageos4microg/lineageos4microg.github.io#65]
There is absolutly **no sound**, neither via headphones nor via speakers, no music, no ringtones, nothing in the **z3** builds from December and January.

In addition, the **fm radio app** cannot be started. It **keeps crashing** upon start.

**I would urge you to remove the last two builds from the download page as soon as possible!**

The November build was fine.

I tried the original lineage build (without microG) from December 24th, which did not have this bug.

Could it be that there is something wrong with the sources you are using.

The original lineage had the sound problem in the October 8th build, but it was solved in the October 15th build.

It would be great if this problem could be solved soon.

Thanks!

**Comment by petefoth** [comment]
Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/
