### ISSUE TITLE
Broken recovery build (davinci)

### ISSUE THREAD

**Issue by Lindstream** [lineageos4microg/lineageos4microg.github.io#66]
Hello,

Spotted an [what I believe to be] "official" recovery build for Davinci, unfortunately it doesn't boot:
https://download.lineage.microg.org/davinci/lineage-17.1-20210115-microG-davinci-recovery.img

Don't know if there's something wrong, or if it wasn't supposed to be published at all - anyhow - it doesn't boot. 

Just letting you know, I'm reverting to my custom recovery+build.

Cheers!

**Comment by thrillfall** [comment]
https://github.com/lineageos4microg/docker-lineage-cicd/issues/143
A working recovery will soon appear

**Comment by petefoth** [comment]
CLosing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
