### ISSUE TITLE
Access to older version

### ISSUE THREAD

**Issue by minedoog** [lineageos4microg/lineageos4microg.github.io#67]
Good day.

Is there an archive or backup for older version of LOS16 with microg? even LOS15?.

I have searched around but I´m unable to find older version for phones that have support on LOS17 already. Only those who do not have support on LOS17 appear to be downloadable on LOS16.

Please, Is there a way to access those older version?

**Comment by petefoth** [comment]
Sorry - no. We don't have disk space to keep old builds around once they are no longer supported.

Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
