### ISSUE TITLE
Updates less than once a month - harpia

### ISSUE THREAD

**Issue by jgreen01** [lineageos4microg/lineageos4microg.github.io#68]
For the harpia ROM, I've noticed that once a month the ROM is built four times in one day.

Here's a screenshot of the website.
![Screenshot_20210306-223145_Firefox](https://user-images.githubusercontent.com/957327/110231304-dc097400-7ecb-11eb-8430-86461e615e82.png)

I would guess that there's something wrong with the scheduling of the builds. Because It seems it's buildings all the roms for the month on one day.

**Comment by Sp1l** [comment]
Those are not 4 separate builds, but 4 files produced by a single build, your screen-width is obfuscating the imporant detail:
```
lineage-17.1-20210414-microG-harpia-recovery.img
lineage-17.1-20210414-microG-harpia.zip
lineage-17.1-20210414-microG-harpia.zip.md5sum
lineage-17.1-20210414-microG-harpia.zip.sha256sum
```

**Comment by jgreen01** [comment]
Ok. I still get updates less than once a month. On your website it says there's weekly builds.

![Screenshot_20210525-105007_Updater](https://user-images.githubusercontent.com/957327/119544949-16eeab80-bd47-11eb-8d00-7362c4c93c36.png)

**Comment by antoinevth** [comment]
The builds are now scheduled to start on the first and 15th of each month (https://github.com/lineageos4microg/docker-lineage-cicd/issues/197#issuecomment-918110759).

**Comment by petefoth** [comment]
Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
