### ISSUE TITLE
Latest (2021-05-06, 2021-05-08) build for Motorola G7 Play/Power (channel, ocean) broken

### ISSUE THREAD

**Issue by Shiandow** [lineageos4microg/lineageos4microg.github.io#77]
The latest builds for channel and ocean (and possibly other motorola g7 phones) are broken and lead to the SIM not being recognized. See https://gitlab.com/LineageOS/issues/android/-/issues/3451 for more information.

As of now it is not possible to downgrade without factory reset, and the fix hasn't landed yet.

I would suggest removing the broken builds, and if possible prioritize a rebuild.

**Comment by Iey4iej3** [comment]
Are you sure that factory reset *suffices*? It seems that you need to *format* data, not only *wiping*, which seem more troublesome. And it seems really better to have more builds - once a month is risky now.

**Comment by Shiandow** [comment]
Well you lose the data partition basically (as the previous build can't read it any more if you downgrade). I may have used the wrong terminology.

**Comment by Iey4iej3** [comment]
If I understand correctly, the crucial issue is that the security patch level is updated. This is why I [proposed](https://github.com/lineageos4microg/docker-lineage-cicd/issues/170) more frequent builds.

**Comment by petefoth** [comment]
Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
