### ISSUE TITLE
Wish: Build / queue / failure status page

### ISSUE THREAD

**Issue by nidico** [lineageos4microg/lineageos4microg.github.io#78]
Is there any kind of status page showing the state of builds / queues / failures?

E.g. I want to look up whether l4m 18.1 is scheduled for cedric and just waiting for its build slot, or if there is a failure occuring.

**Comment by petre2dor** [comment]
Hey, have you found any kind of status page?

**Comment by petefoth** [comment]
You can see the current status of the build in [the dedicated matrix room](https://matrix.to/#/#microg-lineage-os-builds:matrix.domainepublic.net)

Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
