### ISSUE TITLE
Please add Lmi (Poco F2 Pro)

### ISSUE THREAD

**Issue by DavidMoserAI** [lineageos4microg/lineageos4microg.github.io#80]
The poco F2 pro ( Lmi ) is supported by lineage OS but as of yet, is not listed in the download page of microg.

**Comment by antoinevth** [comment]
It is available: https://download.lineage.microg.org/lmi/

This issue should be closed.

**Comment by petefoth** [comment]
Closing and moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/

Please go to the web site, and scroll down to the section 'Where do I report a bug?'. Check out the diagram, and report the issue in the correct place.

Please also see the [Troubleshooting and support](https://github.com/lineageos4microg/docker-lineage-cicd#troubleshooting-and-support) and [Issue Reporting & Tracking](https://github.com/lineageos4microg/docker-lineage-cicd#issue-reporting--tracking) section in the README.md

Thanks
