### ISSUE TITLE
LineageOS 18.1 missing for jfltexx

### ISSUE THREAD

**Issue by rugk** [lineageos4microg/lineageos4microg.github.io#82]
Upstream LineageOS does even have 18.1 builds for the jfltexx: https://download.lineageos.org/jfltexx
LineageOS4microG only has 17.1: https://download.lineage.microg.org/jfltexx/

**Comment by antoinevth** [comment]
See https://github.com/lineageos4microg/docker-lineage-cicd/issues/197

**Comment by petefoth** [comment]
Closing. An up-to-date 18.1 build is available at https://download.lineage.microg.org/jfltexx/

Also Moving this issue to the [docker-lineage-cicd](https://github.com/lineageos4microg/docker-lineage-cicd/issues) issue tracker

This issue tracker is only for issues with our website https://lineage.microg.org/
