### ISSUE TITLE
The site is down

### ISSUE THREAD

**Issue by Axelen123** [lineageos4microg/lineageos4microg.github.io#91]
The Lineageos for MicroG website is down.
I cannot even ping the server.

**Comment by benoit-dardelet** [comment]
The main website is not down for me but the download is not available. (download.lineage.microg.org) Sad this happend on Christmas. Very nice project of you, keep up the good work !

**Comment by bananer** [comment]
I can confirm the web server is unavailable. Might not be able to reach somebody who can help during the holidays though.

**Comment by benoit-dardelet** [comment]
Website is up again, ty

**Comment by Axelen123** [comment]
I can confirm. The site appears to be up again but lineage.microg.org does not appear to have a valid ssl certificate while download.lineage.microg.org does.

**Comment by Axelen123** [comment]
The SSL issue appears to be fixed now and the site is up.

**Comment by kantlivelong** [comment]
Down again?

**Comment by Sapiosenses** [comment]
> Down again?

Not responding here, 2021-10-31 10:15 UTC.

**Comment by Axelen123** [comment]
> Down again?

Seems to be the case.
