### ISSUE TITLE
Mobile Data deactivated after shutdown and restart (18.1/ 20.12.2021). Not shure if other settings also changed

### ISSUE THREAD

**Issue by enoironline** [lineageos4microg/lineageos4microg.github.io#92]
After shutdown and restart my Oneplus 9 Pro Mobile Data is deactivatet, it has to be reactivated in the settings. No Idea how to fix it and if also other settings are similarly affected.

**Comment by Sapiosenses** [comment]
See my comment in #93, probably not LOS4microG related.

**Comment by petefoth** [comment]
If this is still a problem for you, you can try asking in the [LineageOS for microG XDA Forums thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/)

 Closing the issue
