### ISSUE TITLE
Shelter app broken after Shutdown and restart (18.1/20.12.2021)

### ISSUE THREAD

**Issue by enoironline** [lineageos4microg/lineageos4microg.github.io#93]
After restarting my Oneplus 9 Pro, the Shelter app is no longer visible and when I try to install it again it says it is broken. Private and Work profile are still there. I'm presuming it's a OS problem, because aufter a reboot OS settings are changed (see also Issue #92 . 

I am a complete beginner, please for advice on what to do, where to read, how to solve the problem.

**Comment by Sapiosenses** [comment]
> After restarting my Oneplus 9 Pro, the Shelter app is no longer visible and when I try to install it again it says it is broken. Private and Work profile are still there. I'm presuming it's a OS problem, because aufter a reboot OS settings are changed (see also Issue #92 .
> 
> I am a complete beginner, please for advice on what to do, where to read, how to solve the problem.


I suggest you find a regular LOS support venue to answer this, as it probably has nothing to do with the microG components added in this build.

Tip: just mention you are using plain LOS, some of the fora that deal in LOS will not answer questions from people running LOS4microG. (Even if the solution would not be different for either build)

**Comment by petefoth** [comment]
Nothing we can do about this issue here. If this is still a problem for you, you can try asking in the [LineageOS for microG XDA Forums thread](https://forum.xda-developers.com/t/lineageos-for-microg.3700997/)
