### ISSUE TITLE
Missing step: Rebooting to recovery mode (surya) doesn't show LineageOS' recovery menu

### ISSUE THREAD

**Issue by Melonadev** [lineageos4microg/lineageos4microg.github.io#94]
My device is POCO X3 NFC (surya) Global, but here's the [Reddit post](https://www.reddit.com/r/LineageOS/comments/s2xnif/lineage_recovery_not_replacing_miui_recovery) by someone else, discussing this exact issue but for POCO X3 Pro (vayu).

Under 'Installation Instructions' in the [website](https://lineage.microg.org/):

> This ROM has few changes from the official LineageOS ROM, so you can follow the installation guide for your device on the LineageOS wiki.

From **LineageOS for microG**'s [download folder specific to surya](https://download.lineage.microg.org/surya/), I used these two files:
Recovery disc image file: [lineage-18.1-20220122-microG-surya-recovery.img](https://download.lineage.microg.org/surya/lineage-18.1-20220122-microG-surya-recovery.img)
ROM installation zip file: [lineage-18.1-20220122-microG-surya.zip](https://download.lineage.microg.org/surya/lineage-18.1-20220122-microG-surya.zip)

I then followed [LineageOS installation instructions](https://wiki.lineageos.org/devices/surya/install) for my device, until I ran into an issue:
Under the section '[Installing LineageOS from recovery](https://wiki.lineageos.org/devices/surya/install#installing-lineageos-from-recovery)', Step 2 says:

> 2. If you are not in recovery, reboot into recovery:
> - With the device powered off, hold Volume Up + Power. Keep holding both buttons until the “MI” logo appears on the screen, then release.

Necessary commands on host machine, according to LineageOS' installation instructions:
`fastboot flash recovery lineage-18.1-20220122-microG-surya-recovery.img`

What's supposed to show up is the 'MI' logo. Instead, the phone shows the unlocked icon at the top, ‘POCO’ in the middle, and the ‘Android’ logo and name at the bottom.

What’s next is supposed to be LineageOS’ recovery menu, yet the phone shows MIUI’s recovery menu.

The below command solved the issue for me, and actually helped me get to LineageOS’ recovery menu:

`fastboot boot lineage-18.1-20220122-microG-surya.zip`

That command is shown at 4:20 in [this video by Linus Tech Tips](https://www.youtube.com/watch?v=BsHtfLh6azw&t=260). However, LineageOS' website (or the website of LineageOS for microG) doesn't mention it at all.

Before I request an update to the website's instructions, can anyone check if this issue is specific to LineageOS for microG, or LineageOS in general?

**Comment by kurt-by** [comment]
The "with device powered  off" part is a real hurdle for many lineageOS installations. It's not easy to go from fastboot mode to recovery mode without booting system. Booting system in that phase restores original recovery.

**Comment by petefoth** [comment]
> Before I request an update to the website's instructions, can anyone check if this issue is specific to LineageOS for microG, or LineageOS in general?

Sorry we can't check, because we don't have any devices we can test on.

The installation instructions are 'owned' by LineageOS, not by us. But they don't take kindly to issues mentioning microG, so best for you to try installing 'normal' LineageOS, and raising an issue with them based on your experience.

Closing this issue since there's nothing that we can do

**Comment by petefoth** [comment]
Closing
