### ISSUE TITLE
MicroG updating question

### ISSUE THREAD

**Issue by Kommprog** [lineageos4microg/lineageos4microg.github.io#95]
How microG can be updated on any of the _lineageos4microg_ ROMs? There's a new release of [GmsCore](https://github.com/microg/GmsCore/releases), but f-droid doesn't show it neither from available updates nor from searching (microG f-droid repo is on by default). Do I need root to update it manually? Or will it be updated by the next OTA update for device?

**Comment by bananer** [comment]
see https://github.com/microg/GmsCore/issues/424
