### ISSUE TITLE
Ginkgo(redmi note 8) shows up twice + needs update

### ISSUE THREAD

**Issue by Fornball** [lineageos4microg/lineageos4microg.github.io#98]
On https://download.lineage.microg.org/ one can find [gin**kg**o](https://download.lineage.microg.org/ginkgo/) and [gin**gk**o](https://download.lineage.microg.org/gingko/). The gingko device doesnt have any download links and Im pretty sure thats just a typo.

Also, could you recompile the ginko downloads? The official lineageos version is now 18.1, but on lineage4microg its still 17

**Comment by bananer** [comment]
I deleted the typo directory, thanks for pointing it out.

There is a 18.1 build in https://download.lineage.microg.org/ginkgo/ - did you miss it?

**Comment by Fornball** [comment]
Ohh, oops I did indeed miss it
